### ISSUE TITLE
Summary of breaking changes for v0.2

### ISSUE THREAD

**Issue by lehins** [lehins/massiv#20]
Before bumping up a version and introducing breaking changes here is the live list of all of them:

* [x] Remove Eq and Ord instances for Value #19 
* [x] Stencil itself shouldn't care about border resolution #17 
* [x] Rename rank -> dimensions #25

**Comment by lehins** [comment]
All of the planned breaking changes are in master. Ready to make a release.
